version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  ingestion-service:
    build:  ingestion-service/.
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
    environment:
      NODE_ENV: development
      PORT: 3000

  aggregator-core:
    platform: linux/amd64
    build:
      context: ./aggregator-core
    depends_on:
      - rabbitmq
